version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - '5672:5672'
      - '15672:15672'
    container_name: rabbit15672
    environment:
      - RABBITMQ_SERVER= rabbitmq
      - RABBITMQ_DEFAULT_USER=rah
      - RABBITMQ_DEFAULT_PASS=rah